PungPals/PunPals/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("signup/", views.SignUp, name="signup"),
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("<str:username>/", views.UserHome.as_view(), name="user_home"),
    path("<str:username>/create_room/", views.CreateRoom.as_view(), name="create_room"),
    path("<str:username>/join_room/", views.JoinRoom.as_view(), name="join_room"),
    path("<str:username>/delete_room/<int:pk>/", views.DeleteRoom.as_view(), name="delete_room"),
    path("<str:username>/<str:roomname>/", views.RoomHome.as_view(), name="room_home"),
    path("<str:username>/<str:roomname>/register_result3", views.RegisterResult3.as_view(), name="register_result3"),
    path("<str:username>/<str:roomname>/register_result4", views.RegisterResult4.as_view(), name="register_result4"),
    path("<str:username>/<str:roomname>/delete_result3", views.DeleteResult3List.as_view(), name="delete_result3"),
    path("<str:username>/<str:roomname>/delete_taikyoku3/<int:pk>/", views.DeleteResult3.as_view(), name="delete_taikyoku3"),
    path("<str:username>/<str:roomname>/delete_result4", views.DeleteResult4List.as_view(), name="delete_result4"),
    path("<str:username>/<str:roomname>/delete_taikyoku4/<int:pk>/", views.DeleteResult4.as_view(), name="delete_taikyoku4"),
    path("<str:username>/<str:roomname>/ranking", views.Ranking.as_view(), name="ranking"),
]

PungPals/PungPals/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("PungPals/", include("PunPals.urls")),
    path('admin/', admin.site.urls),
]

PungPals/PunPals/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

# Create your models here.
class CustomUserManager(BaseUserManager):
    
    def create_user(self, username, password, **extra_fields):
        if not username or not password:
            raise ValueError("Name and password field must be set")
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        return self.create_user(username, password, **extra_fields), 

class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=100, unique=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = "username"

    objects = CustomUserManager()

    def __str__(self):
        return self.username      

class Room(models.Model):
    name = models.CharField(max_length=100, unique=True)
    passwd = models.CharField(max_length=100)
    users = models.ManyToManyField(CustomUser)

    def __str__(self):
        return self.name

class Taikyoku3(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    userTon = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="taikyoku3_userTon")
    userNan = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="taikyoku3_userNan")
    userSya = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="tiakyoku3_userSya")
    tonScore = models.IntegerField()
    nanScore = models.IntegerField()
    syaScore = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def ranking(self):
        score_list =  [(self.userTon, self.tonScore, 3),
                       (self.userNan, self.nanScore, 2),
                       (self.userSya, self.syaScore, 1)]
        # sort by score and then by user rank in descending order
        score_list.sort(key = lambda x: (x[1], x[2]), reverse=True)
        return [(user.username, score) for user, score, _ in score_list]

class Taikyoku4(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    userTon = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="taikyoku4_userTon")
    userNan = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="taikyoku4_userNan")
    userSya = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="taikyoku4_userSya")
    userPe = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="taikyoku4_userPei")
    tonScore = models.IntegerField()
    nanScore = models.IntegerField()
    syaScore = models.IntegerField()
    peScore = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def ranking(self):
        score_list =  [(self.userTon, self.tonScore, 4),
                       (self.userNan, self.nanScore, 3),
                       (self.userSya, self.syaScore, 2),
                       (self.userPe, self.peScore, 1)]
        # sort by score and then by user rank in descending order
        score_list.sort(key = lambda x: (x[1], x[2]), reverse=True)
        return [(user.username, score) for user, score, _ in score_list]

class Senseki3(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    rankMean = models.FloatField(default=0)
    firstNum = models.IntegerField(default=0)
    secondNum = models.IntegerField(default=0)
    thirdNum = models.IntegerField(default=0)
    outNum = models.IntegerField(default=0)
    firstRate = models.FloatField(default=0)
    secondRate = models.FloatField(default=0)
    thirdRate = models.FloatField(default=0)
    outRate = models.FloatField(default=0)
    gameNum = models.IntegerField(default=0)
    scoreSum = models.BigIntegerField(default=0)
    scoreMean = models.FloatField(default=0)

class Senseki4(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    rankMean = models.FloatField(default=0)
    firstNum = models.IntegerField(default=0)
    secondNum = models.IntegerField(default=0)
    thirdNum = models.IntegerField(default=0)
    fourthNum = models.IntegerField(default=0)
    outNum = models.IntegerField(default=0)
    firstRate = models.FloatField(default=0)
    secondRate = models.FloatField(default=0)
    thirdRate = models.FloatField(default=0)
    fourthRate = models.FloatField(default=0)
    outRate = models.FloatField(default=0)
    gameNum = models.IntegerField(default=0)
    scoreSum = models.BigIntegerField(default=0)
    scoreMean = models.FloatField(default=0)

PungPals/PunPals/views.py
import hashlib

from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, DeleteView, ListView
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.views import View

from .models import CustomUser, Room, Taikyoku3, Taikyoku4, Senseki3, Senseki4
from .form import SignUpForm, CreateRoomForm, JoinRoomForm, Taikyoku3Form, Taikyoku4Form, RankingFilterForm

class Home(TemplateView):
    template_name = "PunPals/home.html"

def SignUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            CustomUser.objects.create_user(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
                )
            return redirect('login')
    else:
        form = SignUpForm()

    return render(request, 'PunPals/signup.html', {'form': form})

class Login(LoginView):
    template_name="PunPals/login.html"

    def get_success_url(self):
        url = reverse('user_home', args=[self.request.user.username]) 
        return url
    
class Logout(LogoutView):
    next_page = reverse_lazy('home')

class UserDispatchMixin:
    def dispatch(self, request, *args, **kwargs):
        if request.user.username != kwargs.get('username'):
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

class UserHome(UserDispatchMixin, LoginRequiredMixin, TemplateView):
    template_name = "PunPals/user_home.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.kwargs.get('username')
        user = CustomUser.objects.get(username=username)
        context['username'] = username
        context['user_rooms'] = user.room_set.all()
        return context

class DeleteRoom(UserDispatchMixin, LoginRequiredMixin, DeleteView):
    model = Room

    def get_success_url(self):
        return reverse('user_home', args=[self.request.user.username])

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())
    
class FormKwargsMixin:
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs
    
class CreateRoom(UserDispatchMixin, FormKwargsMixin, LoginRequiredMixin, CreateView):
    template_name = "PunPals/create_room.html"
    model = Room
    form_class = CreateRoomForm

    def form_valid(self, form):
        password = form.cleaned_data['passwd']
        form.instance.passwd = password

        instance = form.save()

        user = get_user_model().objects.get(username=self.request.user.username)
        instance.users.add(user)

        return HttpResponseRedirect(reverse('room_home', args=[self.request.user.username, instance.name]))

class JoinRoom(UserDispatchMixin, FormKwargsMixin, LoginRequiredMixin, View):
    template_name = "PunPals/join_room.html"

    def get(self, request, *args, **kwargs):
        form = JoinRoomForm(request=request)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = JoinRoomForm(request.POST, request=request)
        if form.is_valid():
            roomname = form.cleaned_data.get('roomname')
            password = form.cleaned_data.get('password')

            room = Room.objects.filter(name=roomname, passwd=password).first()

            if room is None:
                form.add_error(None, '部屋名またはパスワードが違います')
            else:
                room.users.add(request.user)
                room.save()
                return HttpResponseRedirect(reverse('room_home', args=[request.user.username, roomname]))
            
        return render(request, self.template_name, {'form': form})

class RoomDispatchMixin:
    def dispatch(self, request, *args, **kwargs):
        username = kwargs.get('username')
        roomname = kwargs.get('roomname')
        
        user = request.user
        room = get_object_or_404(Room, name=roomname)
        
        if not room.users.filter(id=user.id).exists():
            return HttpResponseRedirect(reverse('user_home', args=[username]))
        return super().dispatch(request, *args, **kwargs)

class RoomHome(UserDispatchMixin, RoomDispatchMixin, LoginRequiredMixin, TemplateView):
    template_name = "PunPals/room_home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.kwargs.get('username')
        roomname = self.kwargs.get('roomname')
        user = get_object_or_404(CustomUser, username=username)
        room = get_object_or_404(Room, name=roomname)

        senseki3 = Senseki3.objects.filter(user=user, room=room).first()
        senseki4 = Senseki4.objects.filter(user=user, room=room).first()

        context['room_users'] = room.users.all()
        context['username'] = username
        context['roomname'] = roomname
        context["room_passwd"] = room.passwd
        context['senseki3'] = senseki3
        context['senseki4'] = senseki4
        return context
    
class RegisterResult3(UserDispatchMixin, RoomDispatchMixin, LoginRequiredMixin, CreateView):
    model = Taikyoku3
    form_class = Taikyoku3Form
    template_name = "PunPals/register_result3.html"

    def get_room(self):
        roomname = self.kwargs.get('roomname')
        return Room.objects.get(name=roomname)
    
    def form_valid(self, form):
        taikyoku3 = form.save(commit=False)
        taikyoku3.room = self.get_room()
        taikyoku3.save()

        ranking = taikyoku3.ranking()

        for index, (username, score) in enumerate(ranking):
            user = CustomUser.objects.get(username=username)
            senseki3, create = Senseki3.objects.get_or_create(user=user, room=taikyoku3.room)

            senseki3.gameNum += 1
            senseki3.scoreSum += score

            if index == 0:
                senseki3.firstNum += 1
            elif index == 1:
                senseki3.secondNum += 1
            elif index == 2:
                senseki3.thirdNum += 1
            if score < 0:
                senseki3.outNum += 1

            senseki3.rankMean = (1 * senseki3.firstNum + 2 * senseki3.secondNum + 3 * senseki3.thirdNum) / float(senseki3.gameNum)
            senseki3.firstRate = senseki3.firstNum / float(senseki3.gameNum) * 100
            senseki3.secondRate = senseki3.secondNum / float(senseki3.gameNum) * 100
            senseki3.thirdRate = senseki3.thirdNum / float(senseki3.gameNum) * 100
            senseki3.outRate = senseki3.outNum / float(senseki3.gameNum) * 100
            senseki3.scoreMean = senseki3.scoreSum / float(senseki3.gameNum)

            senseki3.save()

        return super().form_valid(form)
    
    def get_success_url(self):
        room = self.get_room()
        return reverse('register_result3', kwargs={'username': self.request.user.username, 'roomname': room.name})

    def get_form_kwargs(self):
        kwargs = super(RegisterResult3, self).get_form_kwargs()
        roomname = self.kwargs.get('roomname')
        kwargs['roomname'] = roomname
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.kwargs.get('username')
        context['roomname'] = self.kwargs.get('roomname')
        return context
    
class RegisterResult4(UserDispatchMixin, RoomDispatchMixin, LoginRequiredMixin, CreateView):
    model = Taikyoku4
    form_class = Taikyoku4Form
    template_name = "PunPals/register_result4.html"

    def get_room(self):
        roomname = self.kwargs.get('roomname')
        return Room.objects.get(name=roomname)
    
    def form_valid(self, form):
        taikyoku4 = form.save(commit=False)
        taikyoku4.room = self.get_room()
        taikyoku4.save()

        ranking = taikyoku4.ranking()

        for index, (username, score) in enumerate(ranking):
            user = CustomUser.objects.get(username=username)
            senseki4, create = Senseki4.objects.get_or_create(user=user, room=taikyoku4.room)

            senseki4.gameNum += 1
            senseki4.scoreSum += score

            if index == 0:
                senseki4.firstNum += 1
            elif index == 1:
                senseki4.secondNum += 1
            elif index == 2:
                senseki4.thirdNum += 1
            elif index == 3:
                senseki4.fourthNum += 1
            if score < 0:
                senseki4.outNum += 1

            senseki4.rankMean = (1 * senseki4.firstNum + 2 * senseki4.secondNum + 3 * senseki4.thirdNum + 4 * senseki4.fourthNum) / float(senseki4.gameNum)
            senseki4.firstRate = senseki4.firstNum / float(senseki4.gameNum) * 100
            senseki4.secondRate = senseki4.secondNum / float(senseki4.gameNum) * 100
            senseki4.thirdRate = senseki4.thirdNum / float(senseki4.gameNum) * 100
            senseki4.fourthRate = senseki4.fourthNum / float(senseki4.gameNum) * 100
            senseki4.outRate = senseki4.outNum / float(senseki4.gameNum) * 100
            senseki4.scoreMean = senseki4.scoreSum / float(senseki4.gameNum)

            senseki4.save()

        return super().form_valid(form)
    
    def get_success_url(self):
        room = self.get_room()
        return reverse('register_result4', kwargs={'username': self.request.user.username, 'roomname': room.name})

    def get_form_kwargs(self):
        kwargs = super(RegisterResult4, self).get_form_kwargs()
        roomname = self.kwargs.get('roomname')
        kwargs['roomname'] = roomname
        return kwargs
    

PungPals/PunPals/templates/PunPals/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="icon" type="image/png" href="{% static 'PunPals/icon/favicon.png' %}">
</head>
<body>
     <nav class="navbar navbar-expand-md navbar-light bg-light border-bottom px-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="/PungPals" style="font-size: 1.8rem;">🀄️PungPals</a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                {% if request.user.is_authenticated %}
                <div class="dropdown ms-auto">
                    <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false" style="font-size: 1.5rem;">
                        {{ request.user.username }}
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'user_home' username=request.user.username %}" style="font-size: 1.3rem;">ホーム</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}" style="font-size: 1.3rem;">ログアウト</a></li>
                    </ul>
                </div>
                {% else %}
                {% endif %}
            </div>
        </div>
    </nav>

    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>    
</body>
</html>

PungPals/PunPals/templates/PunPals/create_room.html
{% extends "PunPals/base.html" %}

{% block title %}部屋作成{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container px-4 py-5 my-5 text-center">
    <i class="bi bi-house-add" style="font-size: 3rem;"></i>
    <h2 class="display-5 fw-bold">部屋作成</h2>
    <p class="lead">部屋名・パスワードは変更できません！！安全に保管してください。</p>
    <div class="col-lg-6 mx-auto">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-primary btn-lg">作成</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

PungPals/PunPals/templates/PunPals/delete_result3.html
{% extends "PunPals/base.html" %}

{% block title %}戦績削除{% endblock %}

{% block content %}
<div class="container px-4 py-5 my-5">
  <h2 class="display-5 fw-bold text-center">削除する対局を選んでください</h2>
  <div class="col-lg-6 mx-auto">
    {% if taikyoku3_list %}
      <ul class="list-group">
        {% for taikyoku3 in taikyoku3_list %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ taikyoku3.created_at }}
            <form action="{% url 'delete_taikyoku3' username=username roomname=roomname pk=taikyoku3.pk %}" method="post" class="d-inline">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm">削除</button>
            </form>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>対局結果がありません</p>
    {% endif %}
    <div class="d-grid gap-2 mt-3">
      <button class="btn btn-secondary btn-lg" onclick="location.href='{% url 'room_home' username=username roomname=roomname %}'">戻る</button>  <!-- Reusing button style from register_result3.html -->
    </div>
  </div>
</div>
{% endblock %}

PungPals/PunPals/templates/PunPals/delete_result4.html
{% extends "PunPals/base.html" %}

{% block title %}戦績削除{% endblock %}

{% block content %}
<div class="container px-4 py-5 my-5">
  <h2 class="display-5 fw-bold text-center">削除する対局を選んでください</h2>
  <div class="col-lg-6 mx-auto">
    {% if taikyoku4_list %}
      <ul class="list-group">
        {% for taikyoku4 in taikyoku4_list %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ taikyoku4.created_at }}
            <form action="{% url 'delete_taikyoku4' username=username roomname=roomname pk=taikyoku4.pk %}" method="post" class="d-inline">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm">削除</button>
            </form>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>対局結果がありません</p>
    {% endif %}
    <div class="d-grid gap-2 mt-3">
      <button class="btn btn-secondary btn-lg" onclick="location.href='{% url 'room_home' username=username roomname=roomname %}'">戻る</button>  <!-- Reusing button style from register_result3.html -->
    </div>
  </div>
</div>
{% endblock %}

PungPals/PunPals/templates/PunPals/home.html
{% extends "PunPals/base.html" %}

{% block title %}PungPals{% endblock %}

{% block content %}
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">PungPals</h1>
    <div class="col-lg-6 mx-auto"></div>
        <p class="mt-4 mb-4">あなたの麻雀戦績を残しませんか？<br>
            対局結果を記録することで成長を実感し、戦術の研鑽を積みましょう！
        </p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
            <a href="{% url 'login' %}" class="btn btn-primary btn-lg px-4 gap-3">ログイン</a>
            <a href="{% url 'signup' %}" class="btn btn-outline-secondary btn-lg px-4">新規登録</a>
        </div>
        <div class="d-flex flex-column align-items-center mb-5">
            <i class="bi bi-person-circle text-primary" style="font-size: 4rem;"></i>
            <h5 class="mt-3">アカウントを作成する</h5>
            <p>最初のステップとしてアカウントを作成します。</p>
        </div>
        <div class="d-flex flex-column align-items-center mb-5">
            <i class="bi bi-house text-primary" style="font-size: 4rem;"></i>
            <h5 class="mt-3">部屋を作る、参加する</h5>
            <p>仲間と部屋を作成または部屋に参加して対局を始めましょう。</p>
        </div>
        <div class="d-flex flex-column align-items-center mb-5">
            <i class="bi bi-pencil-square text-primary" style="font-size: 4rem;"></i>
            <h5 class="mt-3">戦績を登録する</h5>
            <p>対局の結果を記録して自分の成長を追跡しましょう。</p>
        </div>
        <div class="d-flex flex-column align-items-center mb-5">
            <i class="bi bi-book text-primary" style="font-size: 4rem;"></i>
            <h5 class="mt-3">自分の戦績やランキングを確認する</h5>
            <p>記録した戦績やランキングをいつでも確認できます。</p>
        </div>
    </div>
</div>
{% endblock %}

PungPals/PunPals/templates/PunPals/join_room.html
{% extends "PunPals/base.html" %}

{% block title %}部屋参加{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container px-4 py-5 my-5 text-center">
    <i class="bi bi-house-up" style="font-size: 3rem;"></i>
    <h2 class="display-5 fw-bold">部屋参加</h2>
    <div class="col-lg-6 mx-auto">
        <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-primary btn-lg">参加</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

PungPals/PunPals/templates/PunPals/login.html
{% extends "PunPals/base.html" %}

{% block title %}login{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container px-4 py-5 my-5 text-center">
    <i class="bi bi-person-circle" style="font-size: 3rem;"></i>
    <h2 class="display-5 fw-bold">ログイン</h2>
    <div class="col-lg-6 mx-auto">
        <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-primary btn-lg">ログイン</button>
            </div>
        </form>
        <div class="mt-3">
            <button onclick="location.href='{% url 'signup' %}'" class="btn btn-link">新規登録へ</button>
        </div>
    </div>
</div>
{% endblock %}

PungPals/PunPals/templates/PunPals/register_result3.html
{% extends "PunPals/base.html" %}

{% block title %}戦績登録{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container px-4 py-5 my-5 text-center">
    <i class="bi bi-pencil-square" style="font-size: 3rem;"></i>
    <h2 class="display-5 fw-bold">戦績登録</h2>
    <div class="col-lg-6 mx-auto">
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-grid gap-2">
                <button class="btn btn-primary btn-lg" type="submit">登録</button>
            </div>
        </form>
        <div class="d-grid gap-2 mt-3">
            <button class="btn btn-secondary btn-lg" onclick="location.href='{% url 'room_home' username=username roomname=roomname %}'">戻る</button>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const form = document.querySelector('form');
        form.addEventListener('submit', function(event) {
            const tonScore = parseInt(document.getElementById('id_tonScore').value, 10);
            const nanScore = parseInt(document.getElementById('id_nanScore').value, 10);
            const syaScore = parseInt(document.getElementById('id_syaScore').value, 10);
            const userTon = document.getElementById('id_userTon').value;
            const userNan = document.getElementById('id_userNan').value;
            const userSya = document.getElementById('id_userSya').value;

            // If the total score is not 105,000 points
            if (tonScore + nanScore + syaScore !== 105000) {
                alert('点数入力に間違いがあります');
                event.preventDefault();
            }

            // If the same user is selected more than once
            if (userTon === userNan || userTon === userSya || userNan === userSya) {
                alert('ユーザーが正しく選択されていません');
                event.preventDefault();
            }
        });
    });
</script>
{% endblock %}

PungPals/PunPals/templates/PunPals/signup.html
{% extends "PunPals/base.html" %}

{% block title %}signup{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container px-4 py-5 my-5 text-center">
    <h2 class="display-5 fw-bold">新規登録</h2>
    <p class="lead">ユーザー名・パスワードは変更できません！！安全に保管してください。</p>
    <div class="col-lg-6 mx-auto">
        <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-primary btn-lg">送信</button>
            </div>
        </form>
        <div class="mt-3">
            <button onclick="location.href='{% url 'login' %}'" class="btn btn-link">ログインへ</button>
        </div>
    </div>
</div>
{% endblock %}